// <auto-generated />
using System;
using FuelStation.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FuelStation.Migrations
{
    [DbContext(typeof(FuelStationContext))]
    [Migration("20210106223417_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FuelStation.Models.FuelType", b =>
                {
                    b.Property<int>("FuelTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("FuelTypeId");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("FuelStation.Models.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("PlanetId");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("FuelStation.Models.PlanetSpaceShipFuelType", b =>
                {
                    b.Property<int>("PlanetSpaceShipFuelTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FuelTypeId");

                    b.Property<int>("PlanetId");

                    b.Property<int?>("SpaceShipId");

                    b.HasKey("PlanetSpaceShipFuelTypeId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("PlanetId");

                    b.HasIndex("SpaceShipId");

                    b.ToTable("PlanetSpaceShipFuelType");
                });

            modelBuilder.Entity("FuelStation.Models.SpaceShip", b =>
                {
                    b.Property<int>("SpaceShipId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("SpaceShipId");

                    b.ToTable("SpaceShips");
                });

            modelBuilder.Entity("FuelStation.Models.PlanetSpaceShipFuelType", b =>
                {
                    b.HasOne("FuelStation.Models.FuelType", "FuelType")
                        .WithMany("SpaceShips")
                        .HasForeignKey("FuelTypeId");

                    b.HasOne("FuelStation.Models.Planet", "Planet")
                        .WithMany("JoinEntries")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FuelStation.Models.SpaceShip", "SpaceShip")
                        .WithMany("FuelTypes")
                        .HasForeignKey("SpaceShipId");
                });
#pragma warning restore 612, 618
        }
    }
}
